src/java/entity/Pobyt.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Collection;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author ondra
 */
@Entity
@Table(name = "POBYT")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Pobyt.findAll", query = "SELECT p FROM Pobyt p"),
    @NamedQuery(name = "Pobyt.findByIdPobytu", query = "SELECT p FROM Pobyt p WHERE p.idPobytu = :idPobytu"),
    @NamedQuery(name = "Pobyt.findByDatumZacatku", query = "SELECT p FROM Pobyt p WHERE p.datumZacatku = :datumZacatku"),
    @NamedQuery(name = "Pobyt.findByDatumKonce", query = "SELECT p FROM Pobyt p WHERE p.datumKonce = :datumKonce"),
    @NamedQuery(name = "Pobyt.findByDatumZacatkuLess", query = "SELECT p FROM Pobyt p WHERE p.datumZacatku BETWEEN :dateToday AND :dateMonth ORDER BY p.cisloPokoje.cisloPokoje"),
    @NamedQuery(name = "Pobyt.findIsRoomFree", query = "SELECT p FROM Pobyt p WHERE ((:dateFrom >= p.datumZacatku AND :dateFrom <= p.datumKonce) OR (:dateTo >= p.datumZacatku AND :dateTo <= p.datumKonce) OR (:dateFrom <= p.datumZacatku AND :dateTo >= p.datumKonce)) AND (:cisloPokoje = p.cisloPokoje.cisloPokoje)"),
    @NamedQuery(name = "Pobyt.findFreeRooms", query = "SELECT p FROM Pobyt p WHERE (:dateFrom >= p.datumZacatku AND :dateFrom <= p.datumKonce) OR (:dateTo >= p.datumZacatku AND :dateTo <= p.datumKonce) OR (:dateFrom <= p.datumZacatku AND :dateTo >= p.datumKonce)"),
    @NamedQuery(name = "Pobyt.findFreeRooms2", query = "SELECT p FROM Pobyt p WHERE (:dateFrom <= p.datumZacatku AND :dateTo <= p.datumZacatku) OR :dateFrom >= p.datumKonce")})

public class Pobyt implements Serializable {
    private static final long serialVersionUID = 1L;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Id
    @Basic(optional = false)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "Pobyt")
    @SequenceGenerator(name="Pobyt", sequenceName = "SEQ_Pobyt", allocationSize = 1) //, allocationSize = 1, initialValue= 1
    @Column(name = "ID_POBYTU")
    private BigDecimal idPobytu;
    @Basic(optional = false)
    @NotNull
    @Column(name = "DATUM_ZACATKU")
    @Temporal(TemporalType.TIMESTAMP)
    private Date datumZacatku;
    @Basic(optional = false)
    @NotNull
    @Column(name = "DATUM_KONCE")
    @Temporal(TemporalType.TIMESTAMP)
    private Date datumKonce;
    @JoinColumn(name = "ID_REZERVACE", referencedColumnName = "ID_REZERVACE")
    @ManyToOne(optional = false)
    private Rezervace idRezervace;
    @JoinColumn(name = "CISLO_POKOJE", referencedColumnName = "CISLO_POKOJE")
    @ManyToOne
    private Pokoj cisloPokoje;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "idPobytu")
    private Collection<SluzbyVPobytu> sluzbyVPobytuCollection;

    public Pobyt() {
    }

    public Pobyt(BigDecimal idPobytu) {
        this.idPobytu = idPobytu;
    }

    public Pobyt(BigDecimal idPobytu, Date datumZacatku, Date datumKonce) {
        this.idPobytu = idPobytu;
        this.datumZacatku = datumZacatku;
        this.datumKonce = datumKonce;
    }

    public BigDecimal getIdPobytu() {
        return idPobytu;
    }

    public void setIdPobytu(BigDecimal idPobytu) {
        this.idPobytu = idPobytu;
    }

    public Date getDatumZacatku() {
        return datumZacatku;
    }

    public void setDatumZacatku(Date datumZacatku) {
        this.datumZacatku = datumZacatku;
    }

    public Date getDatumKonce() {
        return datumKonce;
    }

    public void setDatumKonce(Date datumKonce) {
        this.datumKonce = datumKonce;
    }

    public Rezervace getIdRezervace() {
        return idRezervace;
    }

    public void setIdRezervace(Rezervace idRezervace) {
        this.idRezervace = idRezervace;
    }

    public Pokoj getCisloPokoje() {
        return cisloPokoje;
    }

    public void setCisloPokoje(Pokoj cisloPokoje) {
        this.cisloPokoje = cisloPokoje;
    }

    @XmlTransient
    public Collection<SluzbyVPobytu> getSluzbyVPobytuCollection() {
        return sluzbyVPobytuCollection;
    }

    public void setSluzbyVPobytuCollection(Collection<SluzbyVPobytu> sluzbyVPobytuCollection) {
        this.sluzbyVPobytuCollection = sluzbyVPobytuCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idPobytu != null ? idPobytu.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Pobyt)) {
            return false;
        }
        Pobyt other = (Pobyt) object;
        if ((this.idPobytu == null && other.idPobytu != null) || (this.idPobytu != null && !this.idPobytu.equals(other.idPobytu))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entity.Pobyt[ idPobytu=" + idPobytu + " ]";
    }
    
}

src/java/entity/Users.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author ondra
 */
@Entity
@Table(name = "USERS")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Users.findAll", query = "SELECT u FROM Users u"),
    @NamedQuery(name = "Users.findByUserId", query = "SELECT u FROM Users u WHERE u.userId = :userId"),
    @NamedQuery(name = "Users.findByUsername", query = "SELECT u FROM Users u WHERE u.username = :username"),
    @NamedQuery(name = "Users.findByPassword", query = "SELECT u FROM Users u WHERE u.password = :password"),
    @NamedQuery(name = "Users.findByGroupId", query = "SELECT u FROM Users u WHERE u.groupId = :groupId")})
public class Users implements Serializable {
    @Basic(optional = false)
    @NotNull
    @Column(name = "GROUP_ID")
    private BigInteger groupId;
    private static final long serialVersionUID = 1L;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Id
    @Basic(optional = false)
    //@NotNull
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "MYNOTIFSEQ")
    @SequenceGenerator(name="MYNOTIFSEQ", sequenceName = "SEQ_Users", allocationSize = 1) //, allocationSize = 1, initialValue= 1
    @Column(name = "USER_ID")
    private BigDecimal userId;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 10)
    @Column(name = "USERNAME")
    private String username;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 32)
    @Column(name = "PASSWORD")
    private String password;
    @JoinColumn(name = "ZAKAZNIKID", referencedColumnName = "CISLO_DOKLADU")
    @OneToOne
    private Zakaznik zakaznikid;
    @OneToMany(mappedBy = "fkUsers")
    private Collection<Usergroups> usergroupsCollection;

    public Users() {
    }

    public Users(BigDecimal userId) {
        this.userId = userId;
    }

    public Users(BigDecimal userId, String username, String password) {
        this.userId = userId;
        this.username = username;
        this.password = password;
    }

    public BigDecimal getUserId() {
        return userId;
    }

    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Zakaznik getZakaznikid() {
        return zakaznikid;
    }

    public void setZakaznikid(Zakaznik zakaznikid) {
        this.zakaznikid = zakaznikid;
    }

    @XmlTransient
    public Collection<Usergroups> getUsergroupsCollection() {
        return usergroupsCollection;
    }

    public void setUsergroupsCollection(Collection<Usergroups> usergroupsCollection) {
        this.usergroupsCollection = usergroupsCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (userId != null ? userId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Users)) {
            return false;
        }
        Users other = (Users) object;
        if ((this.userId == null && other.userId != null) || (this.userId != null && !this.userId.equals(other.userId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entity.Users[ userId=" + userId + " ]";
    }

    public BigInteger getGroupId() {
        return groupId;
    }

    public void setGroupId(BigInteger groupId) {
        this.groupId = groupId;
    }
    
}

src/java/jsf/PobytController.java
package jsf;

import entity.Pobyt;
import entity.Rezervace;
import entity.SluzbyVPobytu;
import entity.Users;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.model.DataModel;
import javax.servlet.http.HttpServletRequest;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import org.icefaces.ace.event.SelectEvent;
import session.PobytFacade;

@ManagedBean(name = "pobytController")
@ViewScoped
public class PobytController implements Serializable {

    private Pobyt current;
    
    @EJB
    private session.PobytFacade ejbFacade;
    @EJB
    private session.PokojFacade pokojFacade;
    @EJB
    private session.RezervaceFacade rezervaceFacade;
    @EJB
    private session.UsersFacade usersFacade;
    @EJB
    private session.ZakaznikFacade zakaznikFacade;
    @EJB
    private session.PobytyZakaznikaFacade pobytyZakaznikaFacade;
    private Users user;
    
    private boolean isSelected;
    private List<Pobyt> userPobyts;
    private List<Pobyt> allPobyts;

    public PobytController() {
    }

    public Users getUser() {
        
            FacesContext context = FacesContext.getCurrentInstance();
            HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
            user = usersFacade.findByName(request.getRemoteUser());
        
        return user;
    }

    public void setUser(Users user) {
        this.user = user;
    }

    private PobytFacade getFacade() {
        return ejbFacade;
    }

    public String prepareCreate() {
        current = new Pobyt();
        return "Create";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PobytUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage("Pobyt smazán.");
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, e.toString());
        }

        getAllPobyts();
        getAllUserPobyts();
        return "List";
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PobytDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    public List<Pobyt> getAllPobyts() {
        return (allPobyts = getFacade().findAll());
    }

    public List<Pobyt> getAllUserPobyts() {
        /*
        user = getUser();
        List<Pobyt> p = new ArrayList<Pobyt>();
        for (Rezervace r : zakaznikFacade.findById(user.getZakaznikid().getCisloDokladu()).getRezervaceCollection()) {
            for (Pobyt t : r.getPobytCollection()) {
                p.add(t);
            }
        }
        userPobyts = p;
        return p;
        */
        user = getUser();
        List<Pobyt> l = new ArrayList<Pobyt>();
        for(Pobyt p :ejbFacade.findAll()) {
            if(p.getIdRezervace().getCisloDokladu().getCisloDokladu() == user.getZakaznikid().getCisloDokladu()) {
                l.add(p);
            }
        }
        return l;
        //return pobytyZakaznikaFacade.findById(user.getZakaznikid().getCisloDokladu());
    }

    
    public String getSluzby() {
        String s = "";
        if(current == null) return "null";
        for(SluzbyVPobytu svp : current.getSluzbyVPobytuCollection()) {
            //for(SluzbyVPobytu svp : p.getSluzbyVPobytuCollection()) {
            s+="...";
                s += svp.getIdSluzby().getNazev();
            //}
        }
        return s;
    }
    
    public void selectListener(SelectEvent event) {
        isSelected = true;
        current = (Pobyt) event.getObject();
    }

    public boolean isIsSelected() {
        return isSelected;
    }

    public Pobyt getCurrent() {
        return current;
    }
    
    
}

web/user/pobyt/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ace="http://www.icefaces.org/icefaces/components"
      xmlns:ice="http://www.icesoft.com/icefaces/component">

    <ui:composition template="../../template.xhtml">
        <ui:define name="body">
            <h:form>
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <style type="text/css">
                    /* Important required because row */
                    .ui-datatable-odd {background-color:lightblue !important;}
                </style>
                <ace:dataTable id="showRezervace"
                               value="#{pobytController.allUserPobyts}"
                               var="car"
                               rows="10"
                               paginator="true"
                               paginatorPosition="bottom"
                               selectionMode="single"
                               rowSelectListener="#{pobytController.selectListener}">
                    <ace:column id="id" headerText="Id rezervace" filterBy="#{car.idRezervace.idRezervace}" filterMatchMode="contains">
                        <h:outputText id="idC" value="#{car.idRezervace.idRezervace}"/>
                    </ace:column>
                    <ace:column id="dz" headerText="Datum začátku" filterBy="#{car.datumZacatku}" filterMatchMode="contains">
                        <h:outputText id="dzC" value="#{car.datumZacatku}">
                            <f:convertDateTime pattern="dd. MM. yyyy"></f:convertDateTime>
                        </h:outputText>
                    </ace:column>
                    <ace:column id="dk" headerText="Datum konce" filterBy="#{car.datumKonce}" filterMatchMode="contains">
                        <h:outputText id="dkC" value="#{car.datumKonce}">
                            <f:convertDateTime pattern="dd. MM. yyyy"></f:convertDateTime>
                        </h:outputText>
                            
                    </ace:column>
                    <ace:column id="cp" headerText="Číslo pokoje" filterBy="#{car.cisloPokoje}" filterMatchMode="contains">
                        <h:outputText id="cpC" value="#{car.cisloPokoje}"/>
                    </ace:column>
                </ace:dataTable>
                
                <br/>
                <ace:panel id="personalInfoInputPanel" header="Pobyt"  rendered="#{pobytController.isIsSelected()}">
                    <h:panelGrid id="inputGrid" columns="2" width="25%" styleClass="textEntryInputTable">
                        <h:outputLabel style="font-weight: bold" value="ID rezervace: "/>
                        <h:outputText id="idC" value="#{pobytController.current.idRezervace.idRezervace}"/>
                        <h:outputLabel style="font-weight: bold" value="Datum Začátku"/>
                        <h:outputText id="cdC" value="#{pobytController.current.datumZacatku}">
                                <f:convertDateTime pattern="dd. MM. yyyy"></f:convertDateTime>
                        </h:outputText>
                        <h:outputLabel style="font-weight: bold" value="Datum Konce: "/>
                        <h:outputText id="dvC" value="#{pobytController.current.datumKonce}">
                                <f:convertDateTime pattern="dd. MM. yyyy"></f:convertDateTime>
                        </h:outputText>
                        <h:outputLabel style="font-weight: bold" value="Číslo pokoje:"/>
                        <h:outputText id="dpC" value="#{pobytController.current.cisloPokoje}"/>
                        
                        <h:outputLabel style="font-weight: bold" value="Služby v pobytu: "/>
                        
                        <h:outputText value="Žádné" rendered="#{empty pobytController.current.sluzbyVPobytuCollection}" />
                        <ice:panelSeries var="item" value="#{pobytController.current.sluzbyVPobytuCollection}" rendered="#{not empty pobytController.current.sluzbyVPobytuCollection}">
                            <h:outputText value="#{item.idSluzby.nazev}"/>
                            <h:outputText value=", "/>
                        </ice:panelSeries>
                        
                        
                        <h:commandButton value="Zrušit" action="#{pobytController.destroy()}"/><br/>
                    </h:panelGrid>
                </ace:panel>
            </h:form>
        </ui:define>
    </ui:composition>

</html>