src/java/entity/Pokoj.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author ondra
 */
@Entity
@Table(name = "POKOJ")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Pokoj.findAll", query = "SELECT p FROM Pokoj p"),
    @NamedQuery(name = "Pokoj.findByCisloPokoje", query = "SELECT p FROM Pokoj p WHERE p.cisloPokoje = :cisloPokoje"),
    @NamedQuery(name = "Pokoj.findByPocetLuzek", query = "SELECT p FROM Pokoj p WHERE p.pocetLuzek = :pocetLuzek"),
    @NamedQuery(name = "Pokoj.findByCena", query = "SELECT p FROM Pokoj p WHERE p.cena = :cena"),
    @NamedQuery(name = "Pokoj.findByJeObsazen", query = "SELECT p FROM Pokoj p WHERE p.jeObsazen = :jeObsazen")})
public class Pokoj implements Serializable {
    private static final long serialVersionUID = 1L;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Id
    @Basic(optional = false)
    @NotNull
    @Column(name = "CISLO_POKOJE")
    private BigDecimal cisloPokoje;
    @Basic(optional = false)
    @NotNull
    @Column(name = "POCET_LUZEK")
    private BigInteger pocetLuzek;
    @Basic(optional = false)
    @NotNull
    @Column(name = "CENA")
    private BigInteger cena;
    @Basic(optional = false)
    @NotNull
    @Column(name = "JE_OBSAZEN")
    private BigInteger jeObsazen;
    @OneToMany(mappedBy = "cisloPokoje")
    private Collection<Pobyt> pobytCollection;
    @OneToMany(mappedBy = "cisloPokoje")
    private Collection<PobytyZakaznika> pobytyZakaznikaCollection;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "cisloPokoje")
    private Collection<SluzbyNaPokoji> sluzbyNaPokojiCollection;

    public Pokoj() {
    }

    public Pokoj(BigDecimal cisloPokoje) {
        this.cisloPokoje = cisloPokoje;
    }

    public Pokoj(BigDecimal cisloPokoje, BigInteger pocetLuzek, BigInteger cena, BigInteger jeObsazen) {
        this.cisloPokoje = cisloPokoje;
        this.pocetLuzek = pocetLuzek;
        this.cena = cena;
        this.jeObsazen = jeObsazen;
    }

    public BigDecimal getCisloPokoje() {
        return cisloPokoje;
    }

    public void setCisloPokoje(BigDecimal cisloPokoje) {
        this.cisloPokoje = cisloPokoje;
    }

    public BigInteger getPocetLuzek() {
        return pocetLuzek;
    }

    public void setPocetLuzek(BigInteger pocetLuzek) {
        this.pocetLuzek = pocetLuzek;
    }

    public BigInteger getCena() {
        return cena;
    }

    public void setCena(BigInteger cena) {
        this.cena = cena;
    }

    public BigInteger getJeObsazen() {
        return jeObsazen;
    }

    public void setJeObsazen(BigInteger jeObsazen) {
        this.jeObsazen = jeObsazen;
    }

    @XmlTransient
    public Collection<Pobyt> getPobytCollection() {
        return pobytCollection;
    }

    public void setPobytCollection(Collection<Pobyt> pobytCollection) {
        this.pobytCollection = pobytCollection;
    }

    @XmlTransient
    public Collection<PobytyZakaznika> getPobytyZakaznikaCollection() {
        return pobytyZakaznikaCollection;
    }

    public void setPobytyZakaznikaCollection(Collection<PobytyZakaznika> pobytyZakaznikaCollection) {
        this.pobytyZakaznikaCollection = pobytyZakaznikaCollection;
    }

    @XmlTransient
    public Collection<SluzbyNaPokoji> getSluzbyNaPokojiCollection() {
        return sluzbyNaPokojiCollection;
    }

    public void setSluzbyNaPokojiCollection(Collection<SluzbyNaPokoji> sluzbyNaPokojiCollection) {
        this.sluzbyNaPokojiCollection = sluzbyNaPokojiCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (cisloPokoje != null ? cisloPokoje.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Pokoj)) {
            return false;
        }
        Pokoj other = (Pokoj) object;
        if ((this.cisloPokoje == null && other.cisloPokoje != null) || (this.cisloPokoje != null && !this.cisloPokoje.equals(other.cisloPokoje))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entity.Pokoj[ cisloPokoje=" + cisloPokoje + " ]";
    }
    
}

src/java/jsf/PokojController.java
package jsf;

import entity.Pobyt;
import entity.Pokoj;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import session.PokojFacade;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import org.icefaces.ace.event.SelectEvent;


@ManagedBean(name="pokojController")
@ViewScoped
public class PokojController implements Serializable {


    private Pokoj current;
    private DataModel items = null;
    @EJB private session.PokojFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    private boolean isSelected = false;

    public PokojController() {
    }
    
    public List<Pokoj> getAllPokoje() {
        return ejbFacade.findAll();
    }

    public Pokoj getSelected() {
        if (current == null) {
            current = new Pokoj();
            selectedItemIndex = -1;
        }
        return current;
    }

    private PokojFacade getFacade() {
        return ejbFacade;
    }
    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem()+getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Pokoj)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Pokoj();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            if(getFacade().findByName(current.getCisloPokoje().toString()) != null) {
                JsfUtil.addErrorMessage(null, "Toto["+ current.getCisloPokoje().toString() +"] číslo pokoje již existuje.");
                return null;
            }
            current.setJeObsazen(BigInteger.ZERO);
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PokojCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Pokoj)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PokojUpdated"));
            return "List";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Pokoj)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PokojDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count-1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex+1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass=Pokoj.class)
    public static class PokojControllerConverter implements Converter {

        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PokojController controller = (PokojController)facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "pokojController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.math.BigDecimal getKey(String value) {
            java.math.BigDecimal key;
            key = new java.math.BigDecimal(value);
            return key;
        }

        String getStringKey(java.math.BigDecimal value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value);
            return sb.toString();
        }

        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Pokoj) {
                Pokoj o = (Pokoj) object;
                return getStringKey(o.getCisloPokoje());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: "+Pokoj.class.getName());
            }
        }

    }

    public Pokoj getCurrent() {
        return current;
    }

    public void selectListener(SelectEvent event) {
        isSelected = true;
        current = (Pokoj) event.getObject();
    }

    public boolean isIsSelected() {
        return isSelected;
    }    
    
}

web/admin/pokoj/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="../../template.xhtml">
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreatePokojLabel_cisloPokoje}" for="cisloPokoje" />
                    <h:inputText id="cisloPokoje" value="#{pokojController.selected.cisloPokoje}" title="#{bundle.CreatePokojTitle_cisloPokoje}" required="true" requiredMessage="#{bundle.CreatePokojRequiredMessage_cisloPokoje}"/>
                    <h:outputLabel value="#{bundle.CreatePokojLabel_pocetLuzek}" for="pocetLuzek" />
                    <h:inputText id="pocetLuzek" value="#{pokojController.selected.pocetLuzek}" title="#{bundle.CreatePokojTitle_pocetLuzek}" required="true" requiredMessage="#{bundle.CreatePokojRequiredMessage_pocetLuzek}"/>
                    <h:outputLabel value="#{bundle.CreatePokojLabel_cena}" for="cena" />
                    <h:inputText id="cena" value="#{pokojController.selected.cena}" title="#{bundle.CreatePokojTitle_cena}" required="true" requiredMessage="#{bundle.CreatePokojRequiredMessage_cena}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{pokojController.create}" value="#{bundle.CreatePokojSaveLink}" />
              <br />
              <br />
                <h:link outcome="/index" value="#{bundle.CreatePokojIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/admin/pokoj/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ace="http://www.icefaces.org/icefaces/components">

    <ui:composition template="../../template.xhtml">

        <ui:define name="body">
            <h:form>
                <style type="text/css">
                    /* Important required because row */
                    .ui-datatable-odd {background-color:lightblue !important;}
                </style>
                <ace:dataTable id="showPokoje"
                               value="#{pokojController.allPokoje}"
                               var="s"
                               rows="10"
                               paginator="true"
                               paginatorPosition="bottom"
                               selectionMode="single"
                               rowSelectListener="#{pokojController.selectListener}">
                    <ace:column id="car" headerText="Číslo pokoje" filterBy="#{s.cisloPokoje}" filterMatchMode="contains">
                        <h:outputText id="carCell" value="#{s.cisloPokoje}"/>
                    </ace:column>
                    <ace:column id="name" headerText="Počet lůžek" filterBy="#{s.pocetLuzek}" filterMatchMode="contains">
                        <h:outputText id="nameCell" value="#{s.pocetLuzek}"/>
                    </ace:column>
                    <ace:column id="popis" headerText="Cena" filterBy="#{s.cena}" filterMatchMode="contains">
                        <h:outputText id="namePopis" value="#{s.cena}"/>
                    </ace:column>
                </ace:dataTable>
            
            <!--
            <h:commandLink action="#.{pokojController.prepareView}" />
            <h:outputText value=" "/>
            <h:commandLink action="#.{pokojController.prepareEdit}" />
            <h:outputText value=" "/>
            <h:commandLink action="#.{pokojController.destroy}" />
            -->
            <br/>
                <ace:panel id="personalInfoInputPanel" header="Pobyt"  rendered="#{pokojController.isIsSelected()}">
                    <h:panelGrid id="inputGrid" columns="2" width="25%" styleClass="textEntryInputTable">
                        <h:outputLabel style="font-weight: bold" value="Číslo pokoje: "/>
                        <h:outputText id="idC" value="#{pokojController.current.cisloPokoje}"/>
                        <h:outputLabel style="font-weight: bold" value="Cena: "/>
                        <h:inputText id="cdC" value="#{pokojController.current.cena}"/>
                        <h:outputLabel style="font-weight: bold" value="Počet lůžek: "/>
                        <h:inputText id="dvC" value="#{pokojController.current.pocetLuzek}"/>
                        
                        <h:commandButton value="Změnit" action="#{pokojController.update()}"/>
                        <h:commandButton value="Zrušit" action="#{pokojController.destroy()}"/><br/>
                    </h:panelGrid>
                </ace:panel>
            </h:form>
        </ui:define>
    </ui:composition>

</html>