src/java/jsf/PokojController.java
package jsf;

import entity.Pobyt;
import entity.Pokoj;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import session.PokojFacade;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import org.icefaces.ace.event.SelectEvent;


@ManagedBean(name="pokojController")
@ViewScoped
public class PokojController implements Serializable {


    private Pokoj current;
    private DataModel items = null;
    @EJB private session.PokojFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    private boolean isSelected = false;

    public PokojController() {
    }
    
    public List<Pokoj> getAllPokoje() {
        return ejbFacade.findAll();
    }

    public Pokoj getSelected() {
        if (current == null) {
            current = new Pokoj();
            selectedItemIndex = -1;
        }
        return current;
    }

    private PokojFacade getFacade() {
        return ejbFacade;
    }
    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem()+getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Pokoj)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Pokoj();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            if(getFacade().findByName(current.getCisloPokoje().toString()) != null) {
                JsfUtil.addErrorMessage(null, "Toto["+ current.getCisloPokoje().toString() +"] číslo pokoje již existuje.");
                return null;
            }
            current.setJeObsazen(BigInteger.ZERO);
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PokojCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Pokoj)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PokojUpdated"));
            return "List";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Pokoj)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PokojDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count-1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex+1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass=Pokoj.class)
    public static class PokojControllerConverter implements Converter {

        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PokojController controller = (PokojController)facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "pokojController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.math.BigDecimal getKey(String value) {
            java.math.BigDecimal key;
            key = new java.math.BigDecimal(value);
            return key;
        }

        String getStringKey(java.math.BigDecimal value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value);
            return sb.toString();
        }

        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Pokoj) {
                Pokoj o = (Pokoj) object;
                return getStringKey(o.getCisloPokoje());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: "+Pokoj.class.getName());
            }
        }

    }

    public Pokoj getCurrent() {
        return current;
    }

    public void selectListener(SelectEvent event) {
        isSelected = true;
        current = (Pokoj) event.getObject();
    }

    public boolean isIsSelected() {
        return isSelected;
    }    
    
}

src/java/jsf/RezervaceController.java
package jsf;

import entity.Pobyt;
import entity.Pokoj;
import entity.Rezervace;
import entity.Sluzba;
import entity.SluzbyNaPokoji;
import entity.SluzbyVPobytu;
import entity.Users;
import entity.Zakaznik;
import jsf.util.JsfUtil;
import session.RezervaceFacade;


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.Set;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import org.GNOME.Bonobo.Stream;
import org.icefaces.ace.event.SelectEvent;

@ManagedBean(name = "rezervaceController")
@ViewScoped
public class RezervaceController implements Serializable {

    
    private static final int MONTH = 30;
    private boolean showFields = true;
    private String zakaznici;
    private Map<String, Integer> zakazniciValue = new LinkedHashMap<String, Integer>();
    private List<Integer> cislaPokoju;
    private List<Integer> allCislaPokoju;
    private Rezervace current;
    @EJB
    private session.SluzbyVPobytuFacade sluzbyVPobytuFacade;
    @EJB
    private session.RezervaceFacade ejbFacade;
    @EJB
    private session.PobytFacade pobytFacade;
    @EJB
    private session.PokojFacade pokojFacade;
    @EJB
    private session.ZakaznikFacade zakaznikFacade;
    @EJB
    private session.UsersFacade usersFacade;
    @EJB
    private session.SluzbyNaPokojiFacade sluzbyNaPokoji;
    @EJB
    private session.SluzbaFacade sluzbaFacade;
    private Integer cisloPokoje;
    private Zakaznik zakaznik;
    private Sluzba sluzba;
    private Users user;
    //private List<Rezervace> allUsers;
    boolean isSelected = false;
    private LinkedHashMap<String, Integer> ourSluzby;
    private int summaryPrice;
    private int priceForNight;
    Calendar calendar = Calendar.getInstance();
    private String[] sluzbySelected;
    private Date maxDateBirth;
    private Date dateToday = new Date();
    private Date dateTommorow = new Date(dateToday.getTime() + (24 * 60 * 60 * 1000));
    private Date dateFrom = new Date(dateTommorow.getTime());
    private Date dateTo = new Date(dateTommorow.getTime());

    public void setSluzbySelected(String[] sluzbySelected) {
        this.sluzbySelected = sluzbySelected;
    }

    public String[] getSluzbySelected() {
        return sluzbySelected;
    }

    public Date getMaxDateBirth() {
        return maxDateBirth;
    }

    public Date getDateToday() {
        return dateToday;
    }

    public Date getDateTommorow() {
        return dateTommorow;
    }

    public void updateDateToday() {
        summaryPrice *= 2;
    }

    public void recalculate() {
        if(dateTo != null && dateFrom != null) {
            summaryPrice = 0;
            for (String k : ourSluzby.keySet()) {
                for (String sl : sluzbySelected) {
                    JsfUtil.addSuccessMessage(k);
                    JsfUtil.addSuccessMessage(sl);
                    
                    //JsfUtil.addSuccessMessage(sl);
                    if (ourSluzby.get(k).toString().equals(sl)) {
                        JsfUtil.addSuccessMessage(k);
                        JsfUtil.addSuccessMessage(k.substring(k.indexOf(" "), k.indexOf("Kč)")));
                        summaryPrice += Integer.valueOf(k.substring(k.indexOf(" "), k.indexOf("Kč)")));
                    }
                }
            }
            
            long diff = dateTo.getTime() - dateFrom.getTime();
            long diffDays = diff / (24 * 60 * 60 * 1000);
            summaryPrice += (int) (priceForNight * diffDays);
        }
    }

    public RezervaceController() {
        calendar.add(Calendar.YEAR, -18);
        maxDateBirth = calendar.getTime();

    }

    
    public void setPriceForNight(int priceForNight) {
        this.priceForNight = priceForNight;
    }

    public int getPriceForNight() {
        return priceForNight;
    }

    public void setSummaryPrice(int summaryPrice) {
        this.summaryPrice = summaryPrice;
    }

    public int getSummaryPrice() {
        return summaryPrice;
    }

    public LinkedHashMap<String, Integer> getOurSluzby() {
        if (ourSluzby == null) {
            ourSluzby = ourSluzby();
        }
        return ourSluzby;
    }

    public void setOurSluzby(LinkedHashMap<String, Integer> ourSluzby) {
        this.ourSluzby = ourSluzby;
    }

    public void updateSluzby() {
        priceForNight = pokojFacade.findByName(String.valueOf(cisloPokoje)).getCena().intValue();
        summaryPrice = priceForNight;
        ourSluzby = ourSluzby();
    }

    private LinkedHashMap<String, Integer> ourSluzby() {
        LinkedHashMap<String, Integer> list = new LinkedHashMap<String, Integer>();
        for (SluzbyNaPokoji s : sluzbyNaPokoji.getAllByPokoj(String.valueOf(cisloPokoje))) {
            list.put(s.getIdSluzby().getNazev() + " (" + s.getCenaSluzby() + "Kč)", s.getIdSluzby().getIdSluzby().intValue());
        }
        return list;
    }

    public Rezervace getCurrent() {
        return current;
    }

    public void setCurrent(Rezervace current) {
        this.current = current;
    }

    public void setUser(Users user) {
        this.user = user;
    }

    public Users getUser() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        user = usersFacade.findByName(request.getRemoteUser());

        return user;
    }

    public Sluzba getSluzba() {
        if (this.sluzba == null) {
            this.sluzba = new Sluzba();
        }

        return sluzba;
    }

    public void setSluzba(Sluzba sluzba) {
        this.sluzba = sluzba;
    }

    public void setZakaznik(Zakaznik zakaznik) {
        this.zakaznik = zakaznik;
    }

    public Zakaznik getZakaznik() {
        if (this.zakaznik == null) {
            this.zakaznik = new Zakaznik();
        }
        return zakaznik;
    }

    public List<Rezervace> getAllRezervace() {
        return ejbFacade.findAll();
    }

    public void setCisloPokoje(Integer cisloPokoje) {
        ourSluzby = ourSluzby();
        setOurSluzby(ourSluzby);
        this.cisloPokoje = cisloPokoje;
    }

    public Integer getCisloPokoje() {
        return cisloPokoje;
    }

    public boolean copyList(List dest, List src) {
        if (dest == null) {
            dest = new ArrayList();
        } else {
            dest.clear();
        }
        for (Object o : src) {
            dest.add(o);
        }
        return true;
    }

    public List<Integer> getCislaPokoju() {
        if (cislaPokoju == null) {
            List<Integer> pokoje = new ArrayList<Integer>();
            for (Pokoj p : pokojFacade.findAll()) {
                pokoje.add(p.getCisloPokoje().intValue());
            }
            cislaPokoju = pokoje;
            if (cisloPokoje == null) {
                cisloPokoje = pokoje.get(0);
            }
            allCislaPokoju = new ArrayList<Integer>(cislaPokoju.size());
            copyList(allCislaPokoju, cislaPokoju);
        }
        return cislaPokoju;
    }

    public void setDateFrom(Date date) {
        dateFrom = date;
    }

    public void setDateTo(Date date) {
        dateTo = date;
    }

    public Date getDateFrom() {
        return dateFrom;
    }

    public Date getDateTo() {
        return dateTo;
    }

    public Rezervace getSelected() {
        if (current == null) {
            current = new Rezervace();
        }
        return current;
    }

    private RezervaceFacade getFacade() {
        return ejbFacade;
    }

    public String prepareCreate() {
        current = new Rezervace();
        return "Create";
    }

    public String create() {
        try {
            if(dateFrom.equals(dateTo)) {
                JsfUtil.addErrorMessage("Nemůžete se registrovat na den bez noci.");
                return "";
            }
            if(dateFrom.after(dateTo)) {
                JsfUtil.addErrorMessage("Datum od je po datumu do.");
                return "";
            }
            if(!pobytFacade.getAllFreeRoomsInDates(dateFrom, dateTo, cisloPokoje).isEmpty()) {
                JsfUtil.addErrorMessage("Pokoj je obsazen v tomto termínu.");
                return "";
            }
            
            
            if (user == null) {
                user = getUser();
            }

            if (dateFrom == null || dateTo == null) {
                return null;
            }

            current = new Rezervace();
            //current.setIdRezervace(new BigDecimal(getFacade().findAll().size() + 1));
            current.setDatumPotvrzeni(new Date(Calendar.ERA));
            current.setDatumVytvoreni(new Date());
            current.setDatumZaplaceni(new Date(Calendar.ERA));

            FacesContext context = FacesContext.getCurrentInstance();
            if (context.getExternalContext().isUserInRole("USER")) {
                current.setCisloDokladu(user.getZakaznikid());
            } else if (context.getExternalContext().isUserInRole("MANAGER") && !showFields) {
                current.setCisloDokladu(zakaznikFacade.findById(new BigDecimal(zakaznici)));
            } else {
                zakaznikFacade.create(zakaznik);
                current.setCisloDokladu(zakaznik);
            }
            current.setJeVHistorii(new BigInteger("0"));
            getFacade().create(current);

            Pobyt p = new Pobyt();
            p.setIdRezervace(current);

web/manager/rezervace/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="../../template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditRezervaceTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditRezervaceLabel_idRezervace}" for="idRezervace" />
                    <h:inputText id="idRezervace" value="#{rezervaceController.selected.idRezervace}" title="#{bundle.EditRezervaceTitle_idRezervace}" required="true" requiredMessage="#{bundle.EditRezervaceRequiredMessage_idRezervace}"/>
                    <h:outputLabel value="#{bundle.EditRezervaceLabel_datumVytvoreni}" for="datumVytvoreni" />
                    <h:inputText id="datumVytvoreni" value="#{rezervaceController.selected.datumVytvoreni}" title="#{bundle.EditRezervaceTitle_datumVytvoreni}" required="true" requiredMessage="#{bundle.EditRezervaceRequiredMessage_datumVytvoreni}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditRezervaceLabel_datumPotvrzeni}" for="datumPotvrzeni" />
                    <h:inputText id="datumPotvrzeni" value="#{rezervaceController.selected.datumPotvrzeni}" title="#{bundle.EditRezervaceTitle_datumPotvrzeni}" required="true" requiredMessage="#{bundle.EditRezervaceRequiredMessage_datumPotvrzeni}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditRezervaceLabel_datumZaplaceni}" for="datumZaplaceni" />
                    <h:inputText id="datumZaplaceni" value="#{rezervaceController.selected.datumZaplaceni}" title="#{bundle.EditRezervaceTitle_datumZaplaceni}" required="true" requiredMessage="#{bundle.EditRezervaceRequiredMessage_datumZaplaceni}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditRezervaceLabel_jeVHistorii}" for="jeVHistorii" />
                    <h:inputText id="jeVHistorii" value="#{rezervaceController.selected.jeVHistorii}" title="#{bundle.EditRezervaceTitle_jeVHistorii}" required="true" requiredMessage="#{bundle.EditRezervaceRequiredMessage_jeVHistorii}"/>
                    <h:outputLabel value="#{bundle.EditRezervaceLabel_cisloDokladu}" for="cisloDokladu" />
                    <h:selectOneMenu id="cisloDokladu" value="#{rezervaceController.selected.cisloDokladu}" title="#{bundle.EditRezervaceTitle_cisloDokladu}" required="true" requiredMessage="#{bundle.EditRezervaceRequiredMessage_cisloDokladu}">
                        <f:selectItems value="#{zakaznikController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{rezervaceController.update}" value="#{bundle.EditRezervaceSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditRezervaceViewLink}"/>
                <br />
                <h:commandLink action="#{rezervaceController.prepareList}" value="#{bundle.EditRezervaceShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditRezervaceIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/manager/rezervace/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ace="http://www.icefaces.org/icefaces/components">

    <ui:composition template="../../template.xhtml">
        <ui:define name="body">
            <h:form>
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <style type="text/css">
                    /* Important required because row */
                    .ui-datatable-odd {background-color:lightblue !important;}
                </style>
                <ace:dataTable id="showRezervace"
                               value="#{rezervaceController.allRezervace}"
                               var="car"
                               rows="10"
                               paginator="true"
                               paginatorPosition="bottom"
                               selectionMode="single"
                               rowSelectListener="#{rezervaceController.selectListener}">
                    <ace:column id="id" headerText="id" filterBy="#{car.idRezervace}" filterMatchMode="contains">
                        <h:outputText id="idC" value="#{car.idRezervace}"/>
                    </ace:column>
                    <ace:column id="cd" headerText="Číslo dokladu" filterBy="#{car.cisloDokladu.cisloDokladu}" filterMatchMode="contains">
                        <h:outputText id="cdC" value="#{car.cisloDokladu.cisloDokladu}"/>
                    </ace:column>
                    <ace:column id="dv" headerText="Datum vytvoření" filterBy="#{car.datumVytvoreni}" filterMatchMode="contains">
                        <h:outputText id="dvC" value="#{car.datumVytvoreni}">
                                    <f:convertDateTime pattern="dd. MM. yyyy"></f:convertDateTime>
                        </h:outputText>
                    </ace:column>
                    <ace:column id="dp" headerText="Datum potrvzení" filterBy="#{car.stringOfDatumPotvrzeni()}" filterMatchMode="contains">
                        <h:outputText id="dpC" value="#{car.stringOfDatumPotvrzeni()}"/>
                    </ace:column>
                    <ace:column id="dz" headerText="Datum zaplacení" filterBy="#{car.stringOfDatumZaplaceni()}" filterMatchMode="contains">
                        <h:outputText id="dzC" value="#{car.stringOfDatumZaplaceni()}"/>
                    </ace:column>
                    <!--
                        <h:commandLink action="#.{rezervaceController.prepareView}" value="#.{bundle.ListRezervaceViewLink}"/>
                        <h:outputText value=" "/>
                        <h:commandLink action="#.{rezervaceController.prepareEdit}" value="#.{bundle.ListRezervaceEditLink}"/>
                        <h:outputText value=" "/>
                        <h:commandLink action="#.{rezervaceController.destroy}" value="#.{bundle.ListRezervaceDestroyLink}"/>
                    -->
                </ace:dataTable>

                <br/>
                <ace:panel id="personalInfoInputPanel" header="Rezervace"  rendered="#{rezervaceController.isRowSelected()}">
                    <h:panelGrid id="inputGrid" columns="2" width="25%" styleClass="textEntryInputTable">
                        <h:outputLabel style="font-weight: bold" value="ID: "/>
                        <h:outputText id="idC" value="#{rezervaceController.current.idRezervace}"/>
                        <h:outputLabel style="font-weight: bold" value="Číslo dokladu: "/>
                        <h:outputText id="cdC" value="#{rezervaceController.current.cisloDokladu.cisloDokladu}"/>
                        <h:outputLabel style="font-weight: bold" value="Datum vytvoření: "/>
                        <h:outputText id="dvC" value="#{rezervaceController.current.datumVytvoreni}">
                                    <f:convertDateTime pattern="dd. MM. yyyy"></f:convertDateTime>
                        </h:outputText>
                        <h:outputLabel style="font-weight: bold" value="Datum potrvzení:"/>
                        <h:outputText id="dpC" value="#{rezervaceController.current.stringOfDatumPotvrzeni()}"/>
                        <h:outputLabel style="font-weight: bold" value="Datum zaplacení: "/>
                        <h:outputText id="dzC" value="#{rezervaceController.current.stringOfDatumZaplaceni()}"/>
                        
                        <h:commandButton value="Zrušit" action="#{rezervaceController.destroy()}"/><br/>
                        <h:commandButton value="Potvrdit" action="#{rezervaceController.acceptRezervation()}" rendered="#{facesContext.externalContext.isUserInRole('MANAGER')}"/><br/>
                        <h:commandButton value="Platba OK" action="#{rezervaceController.acceptPayback()}" rendered="#{facesContext.externalContext.isUserInRole('MANAGER')}"/><br/>
                    </h:panelGrid>
                </ace:panel>

            </h:form>
        </ui:define>
    </ui:composition>

</html>